# GitHub Pages Configuration
# This file enables GitHub Pages for the repository

# Site settings
title: "CampLend - DeFi Lending Protocol"
description: "Decentralized lending and borrowing platform on Camp Network blockchain"
url: "https://yamatoeth.github.io"
baseurl: "/CampNetworkLendingPlatform"

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages gem
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - node_modules/
  - contracts/
  - scripts/
  - test/
  - artifacts/
  - cache/
  - package.json
  - package-lock.json
  - hardhat.config.js
  - .env.example
  - README.md

# Include files that start with underscores
include:
  - _config.yml

# Theme (optional)
# theme: minima

# Default layout for pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
